/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    lembaga: Lembaga;
    prestasi: Prestasi;
    fasilitas: Fasilita;
    publikasi: Publikasi;
    kajian: Kajian;
    'phbi-recap': PhbiRecap;
    'sync-runs': SyncRun;
    campaigns: Campaign;
    donors: Donor;
    prayers: Prayer;
    'contact-messages': ContactMessage;
    'webhook-inbox': WebhookInbox;
    'job-runs': JobRun;
    'rate-limits': RateLimit;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    lembaga: LembagaSelect<false> | LembagaSelect<true>;
    prestasi: PrestasiSelect<false> | PrestasiSelect<true>;
    fasilitas: FasilitasSelect<false> | FasilitasSelect<true>;
    publikasi: PublikasiSelect<false> | PublikasiSelect<true>;
    kajian: KajianSelect<false> | KajianSelect<true>;
    'phbi-recap': PhbiRecapSelect<false> | PhbiRecapSelect<true>;
    'sync-runs': SyncRunsSelect<false> | SyncRunsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    donors: DonorsSelect<false> | DonorsSelect<true>;
    prayers: PrayersSelect<false> | PrayersSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'webhook-inbox': WebhookInboxSelect<false> | WebhookInboxSelect<true>;
    'job-runs': JobRunsSelect<false> | JobRunsSelect<true>;
    'rate-limits': RateLimitsSelect<false> | RateLimitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lembaga".
 */
export interface Lembaga {
  id: number;
  nama: string;
  slug?: string | null;
  kategori?: ('pendidikan' | 'operasional') | null;
  deskripsi?: string | null;
  profilImage?: (number | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestasi".
 */
export interface Prestasi {
  id: number;
  lembaga: number | Lembaga;
  title: string;
  event?: string | null;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fasilitas".
 */
export interface Fasilita {
  id: number;
  lembaga: number | Lembaga;
  title: string;
  desc?: string | null;
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi".
 */
export interface Publikasi {
  id: number;
  title: string;
  date: string;
  slug?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kajian".
 */
export interface Kajian {
  id: number;
  type: 'video' | 'artikel' | 'kitab';
  title: string;
  slug?: string | null;
  youtubeId?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pdf?: (number | null) | Media;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phbi-recap".
 */
export interface PhbiRecap {
  id: number;
  rowKey: string;
  event: string;
  year?: string | null;
  date?: string | null;
  description?: string | null;
  image_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-runs".
 */
export interface SyncRun {
  id: number;
  startedAt?: string | null;
  finishedAt?: string | null;
  status?: string | null;
  rowCount?: number | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  title: string;
  slug?: string | null;
  shortDescription?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Media;
  targetAmount?: number | null;
  collectedAmount?: number | null;
  donorCount?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors".
 */
export interface Donor {
  id: number;
  campaignSlug: string;
  clientToken: string;
  name: string;
  amount: number;
  isAnonymous?: boolean | null;
  orderId?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayers".
 */
export interface Prayer {
  id: number;
  token: string;
  campaignSlug?: string | null;
  donorName?: string | null;
  isAnonymous?: boolean | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name?: string | null;
  email?: string | null;
  whatsapp?: string | null;
  rating?: number | null;
  message?: string | null;
  isAnonymous?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-inbox".
 */
export interface WebhookInbox {
  id: number;
  provider: string;
  eventId: string;
  payloadHash?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'done' | 'dead') | null;
  attempts?: number | null;
  nextAttemptAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs".
 */
export interface JobRun {
  id: number;
  name: string;
  lastSuccessAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits".
 */
export interface RateLimit {
  id: number;
  key: string;
  count: number;
  windowStart: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'lembaga';
        value: number | Lembaga;
      } | null)
    | ({
        relationTo: 'prestasi';
        value: number | Prestasi;
      } | null)
    | ({
        relationTo: 'fasilitas';
        value: number | Fasilita;
      } | null)
    | ({
        relationTo: 'publikasi';
        value: number | Publikasi;
      } | null)
    | ({
        relationTo: 'kajian';
        value: number | Kajian;
      } | null)
    | ({
        relationTo: 'phbi-recap';
        value: number | PhbiRecap;
      } | null)
    | ({
        relationTo: 'sync-runs';
        value: number | SyncRun;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'donors';
        value: number | Donor;
      } | null)
    | ({
        relationTo: 'prayers';
        value: number | Prayer;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'webhook-inbox';
        value: number | WebhookInbox;
      } | null)
    | ({
        relationTo: 'job-runs';
        value: number | JobRun;
      } | null)
    | ({
        relationTo: 'rate-limits';
        value: number | RateLimit;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lembaga_select".
 */
export interface LembagaSelect<T extends boolean = true> {
  nama?: T;
  slug?: T;
  kategori?: T;
  deskripsi?: T;
  profilImage?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestasi_select".
 */
export interface PrestasiSelect<T extends boolean = true> {
  lembaga?: T;
  title?: T;
  event?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fasilitas_select".
 */
export interface FasilitasSelect<T extends boolean = true> {
  lembaga?: T;
  title?: T;
  desc?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi_select".
 */
export interface PublikasiSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kajian_select".
 */
export interface KajianSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  slug?: T;
  youtubeId?: T;
  body?: T;
  pdf?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phbi-recap_select".
 */
export interface PhbiRecapSelect<T extends boolean = true> {
  rowKey?: T;
  event?: T;
  year?: T;
  date?: T;
  description?: T;
  image_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-runs_select".
 */
export interface SyncRunsSelect<T extends boolean = true> {
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  rowCount?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  coverImage?: T;
  targetAmount?: T;
  collectedAmount?: T;
  donorCount?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors_select".
 */
export interface DonorsSelect<T extends boolean = true> {
  campaignSlug?: T;
  clientToken?: T;
  name?: T;
  amount?: T;
  isAnonymous?: T;
  orderId?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayers_select".
 */
export interface PrayersSelect<T extends boolean = true> {
  token?: T;
  campaignSlug?: T;
  donorName?: T;
  isAnonymous?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  whatsapp?: T;
  rating?: T;
  message?: T;
  isAnonymous?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-inbox_select".
 */
export interface WebhookInboxSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  payloadHash?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs_select".
 */
export interface JobRunsSelect<T extends boolean = true> {
  name?: T;
  lastSuccessAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits_select".
 */
export interface RateLimitsSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  windowStart?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tentangKami?: {
    visi?: string | null;
    misi?:
      | {
          teks?: string | null;
          id?: string | null;
        }[]
      | null;
    detail?: string | null;
  };
  kontak?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    mapEmbedUrl?: string | null;
    hours?: string | null;
  };
  sosial?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  sheetMapping?: {
    eventColumn?: string | null;
    yearColumn?: string | null;
    dateColumn?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tentangKami?:
    | T
    | {
        visi?: T;
        misi?:
          | T
          | {
              teks?: T;
              id?: T;
            };
        detail?: T;
      };
  kontak?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        mapEmbedUrl?: T;
        hours?: T;
      };
  sosial?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  sheetMapping?:
    | T
    | {
        eventColumn?: T;
        yearColumn?: T;
        dateColumn?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}